---
title: Jordan Koschei
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
email: jordan@jordankoschei.com
description: Jordan Koschei is a product designer and writer who lives and works in the Hudson Valley.
timezone: America/New_York
baseurl: 
# url: https://jordankoschei.com
permalink: "/:title/"
paginate: 20
paginate_path: "/writing/:num/"
twitter_username: jordankoschei
github_username: jordankoschei
future: false
markdown: kramdown
destination: _site
defaults:
-
  scope:
    path: ""
    type: "posts"
  values:
    layout: "post"
plugins:
- jekyll-paginate
- jekyll-archives
- jekyll-sitemap
jekyll-archives:
  enabled:
  - categories
  layout: archive
  permalinks:
    category: "/writing/:name/"